### ISSUE TITLE
When is a publication domain and/or escience?

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/rsd-instruction#1]
The last point of adding a publication is about whether it is domain or escience.

For example http://dx.doi.org/10.1021/acs.jcim.6b00686 is about a Virtual Machine provisioning, KNIME nodes and scientific workflows. So should I use both tags: escience for the VM and nodes and domain for the workflows?

**Comment by lodekulik** [comment]
eScience publication = any publication with the computer science community as target audience 
Domain science publication = any publication with a domain science community as target audience 

The above is therefore a domain science publication
