### ISSUE TITLE
Click Netherlands eScience Center in Group Libraries?

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/rsd-instruction#10]
The instruction "Click Netherlands eScience Center in Group Libraries." is unclear to me. 

This is my screen and I do not see 'Group libraries':
![zotero_print_screen](https://user-images.githubusercontent.com/8362333/31668640-0a209492-b353-11e7-9be5-c35a54544dfe.png)

An illustration with picture of where to click might help.

**Comment by Tommos0** [comment]
Hi, I see on the top right there is a red icon. This probably means there is an error synchronizing with your  Zotero account. Can you hover / click on it so it shows what is wrong?

**Comment by vincentvanhees** [comment]
Restarting Zotero fixed it, i can now see the Group Libraries
