### ISSUE TITLE
Don't know how to fill in the date

### ISSUE THREAD

**Issue by Maartenvm** [NLeSC/rsd-instruction#15]
Dates in zotero are freeform, and if dates are important to us this needs restrictions because we cannot parse "4-5th December 2013"

**Comment by lodekulik** [comment]
Goed punt. Erg belangrijk voor ons ivm jaarlijkse rapportage. Heb jij hier een oplossing voor @Tommos0 ?

**Comment by Tommos0** [comment]
I'm gonna use [dateparser](https://pypi.python.org/pypi/dateparser) to parse the dates.
This means that

> In [4]: dateparser.parse('4-5th December 2013')
> Out[4]: datetime.datetime(2013, 12, 4, 0, 0)

I think we should refrain from using date ranges, and just use single date (the first day of the range).
To differentiate days from months, please use `yyyy-mm-dd`, or `yyyy/mm/dd`. If the year is last `dateparser` will parse it as `mm-dd-yyyy`, and zotero will also show it as such, so anything like **`dd-mm-yyyy` will not parse correctly**.
If the day is unknown, use `mm yyyy`.
I'll update the guide too
