### ISSUE TITLE
Do we want to add this? #hoedan ?

### ISSUE THREAD

**Issue by Maartenvm** [NLeSC/rsd-instruction#16]
Knowledge exchange/ Networking acitivity

Summerschool

ARIADNE (European Commission Seventh Framework Programme under grant agreement FP7-INFRASTRUCTURES-2012-1-313193 (ARIADNE)

episode: 2D/3D documentation for archaeology (ISTI-CNR)

http://ariadne-infrastructure.eu/

**Comment by lodekulik** [comment]
How where you involved? Presentation? Lecture? Are those possible catergories (or if not why not)?

**Comment by sverhoeven** [comment]
Me,  Rens and Oscar went to Pisa for a week to learn about 3D aquisition, 3D software (meshlab), 3D printing. We demonstrated our Via Appia viewer and added their mesh visualization (3DHop) to the viewer.

**Comment by lodekulik** [comment]
Is there any record of this (mentioning you)? In that case I would call this a presentation, and if there's no record I think it should be skipped (hard to justify the claim). What do you think?

**Comment by Tommos0** [comment]
I don't think we have to justify every claim, this is gonna be impossible for most presentations.
It's probably best to add this as a `presentation` and be clear about it in the Title / Description eg. `Presented Via Appia viewer at ARIADNE summer school 201x`, and fill the `location` & `date` fields.

**Comment by lodekulik** [comment]
Can we close this issue @Maartenvm ?
