### ISSUE TITLE
Do we add this somehow? What about only the accepted things? PhD proposals?

### ISSUE THREAD

**Issue by Maartenvm** [NLeSC/rsd-instruction#17]
Research Propsals

Under review

NWO large: Rediscovering Landscape (outcome beginning of 2016)

NWO Free Competition: Digital Cultural Biography of Testaccio in 3D (outcome beginning of 2016)

**Accepted**

**PhD proposal | HLCS : R. de Hond (start september 2015)**

**Comment by lodekulik** [comment]
Hmmmm I don't know, it seems a little too far fetched. We're trying to capture so much now that we have to consider what we are actually recording. I think proposals shouldn't be considered project output in this case. What is your own opinion?

**Comment by jspaaks** [comment]
No need to add that
