### ISSUE TITLE
Extended projects

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/rsd-instruction#18]
The embodied emotions project was extended with external funding. Now there are two projects, and I'm responsible for both. It is not clear where to add which output, it seems much more straightforward to add everything to the main project and ignore the project extension. I guess there can be project extensions where it is clear what output belongs where, but in this case it doesn't. All papers were written in extension time.

**Comment by lodekulik** [comment]
I think it is fine to add them only to the main project. We will also take this issue to the sprint.

**Comment by jspaaks** [comment]
Agree with Lode, add them to main project
