### ISSUE TITLE
Slide sharing

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/rsd-instruction#20]
To my understanding a presentation in zotero is an event, not a slide deck, is this correct?

If we want to share the slides of a presentation, where do we upload them? The same question can be asked about posters.

**Comment by Tommos0** [comment]
I think the best options are either Zenodo or Figshare, they both give your content a DOI and have an online viewer.

**Comment by lodekulik** [comment]
It's a good question, let's discuss this at the sprint as well. Another options I heared earlier is SlideShare. Do you have any other ideas @jvdzwaan ?

**Comment by jvdzwaan** [comment]
I also looked at SpeakerDeck and slider.io (see https://github.com/NLeSC/guide/issues/105), but definitely prefer Zenodo or Figshare over these or over SlideShare.

**Comment by jspaaks** [comment]
do what @Tommos0 says
