### ISSUE TITLE
Conference abstracts vs. presentations

### ISSUE THREAD

**Issue by jvdzwaan** [NLeSC/rsd-instruction#22]
For some conferences, you write an abstract and if it is accepted, you give a presentation. How to add this type of research output?

**Comment by Tommos0** [comment]
I'm not sure if we should make this one or two items. @lodekulik, maybe any ideas?

**Comment by lodekulik** [comment]
I would make this two items, one as a reference to the conference and one as a presentation on figshare/slideshare/zenodo (to be discussed during sprint)

**Comment by jspaaks** [comment]
indeed, as two items
