### ISSUE TITLE
Software carpentry / essential skills

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/rsd-instruction#25]
Should these be included as `Presentation` with `type: workshop`

**Comment by lodekulik** [comment]
Not sure, they aren't project output. But publications in miscellaneous aren''t project output either.
We'll take your question to the sprint.

**Comment by c-martinez** [comment]
They are an output from the center, right?

**Comment by lodekulik** [comment]
That's true, but we don't necessarily have to, or can, record all output of the center in Zotero. The symposium or other events for example are also not in Zotero, as are our policy reports. I think it should be limited to research output - but we'll have a look at this during the sprint.

**Comment by jspaaks** [comment]
I think we should find a way to include this type of contribution. Will discuss.

**Comment by jspaaks** [comment]
OK, so if you make materials: upload them. If it's teaching existing materials, we consider this more of event, and don;t record it as output. (sorry Carlos ;)

**Comment by c-martinez** [comment]
:-( -- fine, that works for me :-)
