### ISSUE TITLE
TraiT and 2 more projects

### ISSUE THREAD

**Issue by elboyran** [NLeSC/rsd-instruction#26]
I am put responsible for 5 projects, including TraIT. But I do not know anything about it and wasn'tinvolve at all. Rita was the coordinator and Ruud was the engineer. Both have left, but Lars is now the Life Sciencies sector coordinator, so he might know more than me?

**Comment by elboyran** [comment]
Furthermore, there is no output of this project (in the sense we define it): no papers, no software. I see only power point presentations... 
[Project Products](https://nlesc.sharepoint.com/sites/operations/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x0120001A213E64C8D7E54D8BFB41016C82CC80&id=%2Fsites%2Foperations%2FShared%20Documents%2FProjectportfolio%2FCompleted%20projects%2F27011309%20Life%20SciencesTraIT%2FD%2D%20Products)
I would remove it from  the list actually...

**Comment by ridderl** [comment]
I'll try to find some references for the Trait project.

**Comment by elboyran** [comment]
I have asked Noura about missing end reports for TraIT and 2 other old projects, but she also doesn't know about such document! They were also odd, so called Enlighten Your Research (EYR), path-finder like and I personally would remove them from the list...


Code | Title
-- | --
27014502 | Achieving   Multidisciplinary High-Throughput
27014501 | A Lightpath for Optical Coherence Tomography imaging
27011309 | Life Sciences/TraIT

**Comment by ridderl** [comment]
I added 3 items for TraIT, which I could find online (2 conference abstracts and one report), and which had NLeSC affiliation / partnerships mentioned.

**Comment by elboyran** [comment]
Thanks!

**Comment by jspaaks** [comment]
Looks good to us, can consider this done.
