### ISSUE TITLE
Software by partners in projects

### ISSUE THREAD

**Issue by elboyran** [NLeSC/rsd-instruction#28]
Do we add project software mostly developed by partners, but for the project?
Especially if our software was not agreed to be open source by other project partners?
And if we decide to cite it, how if it doesn't have a DOI and we're not the repo owners to make one....
I have this issue in Biomarker, please see the READMEs:
[BiomarkerBosting](https://github.com/NLeSC/biomarker_boosting/blob/master/README.md)
[FancyPipe](https://github.com/rbakker/MultiAtlasRegistration/blob/master/README.md)

**Comment by Tommos0** [comment]
We will discuss this during the sprint!

**Comment by jspaaks** [comment]
It's fine not to include this, since we don't see how we can fill in enough data to fill the software product page, e.g. what happens if a user clicks on "Get started" it's not clear where the data for the activity chart comes from (since the repo is private), etc.
