### ISSUE TITLE
Add new code for other research projects

### ISSUE THREAD

**Issue by arnikz** [NLeSC/rsd-instruction#30]
Sometimes we (co-)author papers (with NLeSC affiliation) that are not directly related to our projects or funded by NLeSC. How should we report these (e.g. [doi:10.1371/journal.pone.0170762](https://doi.org/10.1371/journal.pone.0170762)) in Zotero? Perhaps category 'miscellaneous'?

**Comment by Tommos0** [comment]
Yes, please add them to `Miscellaneous`, which is in Zotero on the same level as `Projects`. We can see what we do with these later.
