### ISSUE TITLE
Add poster using its DOI

### ISSUE THREAD

**Issue by arnikz** [NLeSC/rsd-instruction#31]
I've got posters published on Zenodo but can't add them in Zotero via DOI.

Error message:

`Zotero could not find a record for the specified identifier. Please verify the identifier and try again.`

**Comment by Tommos0** [comment]
Was this DOI recently created? It sometimes takes a while before Zotero can look it up. If not, what is the DOI?

**Comment by arnikz** [comment]
The poster was made in 2015. I've tried today and it works! Apparently, there was something with the Zenodo service yesterday.
