### ISSUE TITLE
Prize ?

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/rsd-instruction#33]
Should I add this one?

http://www.beeldengeluid.nl/en/blogs/researchampdevelopmenten/201706/divereceivesgrandprizelodlamsummitvenice

How?

**Comment by jspaaks** [comment]
if I read the instructions correctly, blog posts can be added as described here https://github.com/NLeSC/rsd-instruction/blame/6837402cae07b567d78b5159ee090aa5acf4b689/README.md#L158-L160

I'm not sure what to do about the prize itself. I feel that it is something worth listing, isnt it? But not sure how. Will discuss.

**Comment by jspaaks** [comment]
So we decided that it's diffifult to add the prize, but you should add the blog
