### ISSUE TITLE
Sherlock output

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/rsd-instruction#34]
In the Sherlock team building we made https://github.com/nlesc-sherlock/ repos, there is no Sherlock project. To which folder should these be added?

**Comment by Tommos0** [comment]
Is it not related to any project or is the project missing? In the former case, please add it to Miscellaneous

**Comment by jspaaks** [comment]
ok so we will merge ``estep 2016``, ``estep 2017`` and ``estep``  into one ``estep``, please fill in any sherlock related item there.
