### ISSUE TITLE
Link publications and software outside group?

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/rsd-instruction#4]
https://doi.org/10.5281/zenodo.240491 is a client for http://gpcrdb.org/ web service which must be cited using http://dx.doi.org/10.1093/nar/gkv1178 . 

The current instructions tell you to link software to publication, but when I try it only allows me to link to things already inside Zotero. 

So what should I do? Link it somehow or ignore it?

**Comment by lodekulik** [comment]
We do not link items within Zotero. Can @Tommos0 confirm?

**Comment by Tommos0** [comment]
Can confirm **no linking in Zotero**, we will add additional metadata and links in a later stage (RSD admin interface).
