### ISSUE TITLE
Academic titles in PI names?

### ISSUE THREAD

**Issue by vincentvanhees** [NLeSC/rsd-instruction#46]
For external communication it is important that we get the academic titles of PIs correct and consistent.
I see the following solutions:
- Clarify it at the entry field, e.g. please include academic title
- Review manually afterward
- Academic title as a separate entry field

**Comment by Tommos0** [comment]
@jmaassen @lodekulik what to do about this?

**Comment by jspaaks** [comment]
We won't record any academic titles, and we won't use them in the front end.
