### ISSUE TITLE
Software Paper?

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/rsd-instruction#5]
In the instructions it also mentions a `Software Paper`. 
What is the definition of it? A publication in a computer science journal?

Is my example (http://dx.doi.org/10.1021/acs.jcim.6b00686) a software paper?

**Comment by Tommos0** [comment]
Best to classify this as a normal `Journal Article`, it's published in a domain journal, eg. it targets chemists and not computer (e)scientists
