### ISSUE TITLE
Where to put software logo?

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/rsd-instruction#51]
There is no field in Zotero or RSD to put software logo url or upload an image.

- mcfly: https://github.com/NLeSC/mcfly/blob/master/mcflylogo.png
-

**Comment by Tommos0** [comment]
We will add this functionality later, for now please add an issue with label `logo` in this repository and add where to find the image + the software it corresponds to

**Comment by cwmeijer** [comment]
mcfly url added to original post

**Comment by jspaaks** [comment]
@Tommos0 maybe also have peeps add a key ``logo`` in the Extra field like we suggest for data sets?

**Comment by jspaaks** [comment]
there is no need to put in any information regarding the logos of software.
