### ISSUE TITLE
Creators section do not cover all posibitlities

### ISSUE THREAD

**Issue by elboyran** [NLeSC/rsd-instruction#53]
If the contact person is the main and only contributor, adding the name makes Contributors section appear, but it's empty, i.e. the main contributor is not listed. On the other hand if a contact person has not written the software, but 'inherited' it from for ex. an ex-colleague, the person apears as a Creator- contact person, so perhaps Creators is not the best name for the section.

**Comment by jspaaks** [comment]
related issue by LourensVeen : we should avoid claiming ownership of tools that are not originally ours.

**Comment by jiskattema** [comment]
For LourensVeen's issue: For significant contributions (enough so that we want to add it to RSD), i've been adding *type: Feature* to the *Extra* field

**Comment by jspaaks** [comment]
So we will no longer use the term Creator but instead label all people involved as Contributor (of software, of ideas, of opinions, of whatever), and (possibly) label one of those as contact person.
