### ISSUE TITLE
No Github ID

### ISSUE THREAD

**Issue by egpbos** [NLeSC/rsd-instruction#55]
I have one project on Bitbucket. Obviously, this has no Github ID. What to do with this?

**Comment by Tommos0** [comment]
Please add it anyway in Zotero. If the code is public you can still make a Zenodo DOI by uploading an archive.

**Comment by egpbos** [comment]
Yes, it was already in Zotero, I was confused by the fact that there are two PIDIMEHS library entries in the RSD ("PIDIMEHS library" and "PIDIlib"), so never mind :)
