### ISSUE TITLE
Data set identified as journal article

### ISSUE THREAD

**Issue by egpbos** [NLeSC/rsd-instruction#56]
I entered a data set in Zotero, but it is recognized as a journal article: http://test.research-software.nl/software/pidimehs-library

**Comment by jspaaks** [comment]
see also relevant section here https://github.com/NLeSC/rsd-instruction/blame/6837402cae07b567d78b5159ee090aa5acf4b689/README.md#L124-L128

**Comment by egpbos** [comment]
Ok, I did add that field, but forgot that it was a workaround and will be fixed in the future.

**Comment by jspaaks** [comment]
that's ok, i added it here mostly as a note to my future self ;)
