### ISSUE TITLE
add to instructions

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/rsd-instruction#58]
The current instructions cover the 'enter data in zotero' phase, but does not cover the rsd form at ``http://admin.research-software.nl/``. I'd like to expand the instruction to also cover that, as well as how to see how the data you just added is being used at ``http://test.research-software.nl``, so that people can have some reward for their effort of entering data.

**Comment by Tommos0** [comment]
nlesc/rsd-instruction#72fdc22

**Comment by jspaaks** [comment]
Looks good
