### ISSUE TITLE
Software from Zenodo item type Document or Computer Program

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/rsd-instruction#6]
When adding a software release doi from Zenodo, for example https://doi.org/10.5281/zenodo.240491 then Zotero has item type `Document`. 

While there also is the item type `Computer Program`, should we not use that?

**Comment by Tommos0** [comment]
Please use `Computer Program` for clarity, although I will process any `Document` that has a Zenodo / GitHub URL as software too
